apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-microservice
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: sample-microservice
    spec:
      containers:
      - name: sample-microservice
        image: registry.ng.bluemix.net/{namespace}/sample-microservice:latest
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 100Mi

---

apiVersion: v1
kind: Service
metadata:
  name: sample-microservice-external
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  #type: LoadBalancer
  type: NodePort
  ports:
  # the port that this service should serve on
  - name: http
    port: 8080

  selector:
    app: sample-microservice
